package tool1.mapping;

public enum DBFileds {

	DBAID("DBAID"), ZYCUSSUPPLIERID("ZYCUSSUPPLIERID"), TAXCODE("TAXIDCODE"), TAXFORMAT("TAXIDFORMAT"), NAME(
			"NAME"), NAMETYPE("NAMETYPE"), SUPPLIERSTATUS("SUPPLIERSTATUS"), APPROVALSTATUS(
					"APPROVALSTATUS"), LOCATIONTYPE("LOCATIONTYPE"), CREATEDATE("CREATEDATE"), MODIFIEDDATE(
							"MODIFIEDDATE"), SEPARATEADDRESS("SEPARATEADDRESS"), CLIENTID("CLIENTID"), SUPPLIERTYPE(
									"SUPPLIERTYPE"), GSID("DISPLAYGSID"), SUPPLIERTOKENID(
											"SUPPLIERTOKENID"), COMPANY_TYPE("COMPANY_TYPE");
	private String value;

	public String getValue() {
		return "\"" + value + "\"";
	}

	private DBFileds(String value) {
		this.value = value;
	}

}
